-- Create enum type "purchaseorderitems_status"
CREATE TYPE "public"."purchaseorderitems_status" AS ENUM ('open', 'received', 'in_review');
-- Create enum type "purchaseorders_status"
CREATE TYPE "public"."purchaseorders_status" AS ENUM ('open', 'received', 'in_review');
-- Create enum type "vendoritemprice_post_type"
CREATE TYPE "public"."vendoritemprice_post_type" AS ENUM ('DEEP', 'NO_POST', 'SHALLOW');
-- Create enum type "posttype"
CREATE TYPE "public"."posttype" AS ENUM ('DEEP', 'SHALLOW', 'NO_POST');
-- Create enum type "item_status"
CREATE TYPE "public"."item_status" AS ENUM ('ACTIVE', 'INACTIVE', 'DELETED');
-- Create "entity" table
CREATE TABLE "public"."entity" ("name" character varying(255) NULL, "id" bigserial NOT NULL, PRIMARY KEY ("id"));
-- Create "employee" table
CREATE TABLE "public"."employee" ("id" integer NOT NULL GENERATED ALWAYS AS IDENTITY, "created_date" timestamptz NULL DEFAULT CURRENT_TIMESTAMP, "name" character varying(255) NULL, "pin" character varying(255) NULL, "entity_id" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "employee_entity_id_fk" FOREIGN KEY ("entity_id") REFERENCES "public"."entity" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "employeetimerecord" table
CREATE TABLE "public"."employeetimerecord" ("id" integer NOT NULL GENERATED ALWAYS AS IDENTITY, "punch_in_time" timestamptz NULL DEFAULT CURRENT_TIMESTAMP, "punch_out_time" timestamptz NULL, "employee_id" integer NULL, PRIMARY KEY ("id"), CONSTRAINT "employeetimerecord_employee_id_fk" FOREIGN KEY ("employee_id") REFERENCES "public"."employee" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "idx_16966_fkkheveglahdwi5rsohfordpbgc" to table: "employeetimerecord"
CREATE INDEX "idx_16966_fkkheveglahdwi5rsohfordpbgc" ON "public"."employeetimerecord" ("employee_id");
-- Create "department" table
CREATE TABLE "public"."department" ("name" character varying(255) NOT NULL, "tax" numeric(38,4) NOT NULL, "bottledeposit" numeric(38,2) NOT NULL, "environmentfee" numeric(38,2) NOT NULL, PRIMARY KEY ("name"));
-- Create "item" table
CREATE TABLE "public"."item" ("itemseqno" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10418), "barcode" character varying(255) NULL, "barcode2" character varying(255) NULL, "caseqty" integer NOT NULL DEFAULT 0, "changeby" character varying(255) NULL, "changedate" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, "comments" character varying(255) NULL, "cyaprsold" numeric(38,2) NOT NULL DEFAULT 0, "cyaugsold" numeric(38,2) NOT NULL DEFAULT 0, "cydecsold" numeric(38,2) NOT NULL DEFAULT 0, "cyfebsold" numeric(38,2) NOT NULL DEFAULT 0, "cyjansold" numeric(38,2) NOT NULL DEFAULT 0, "cyjulsold" numeric(38,2) NOT NULL DEFAULT 0, "cyjunsold" numeric(38,2) NOT NULL DEFAULT 0, "cymarsold" numeric(38,2) NOT NULL DEFAULT 0, "cymaysold" numeric(38,2) NOT NULL DEFAULT 0, "cynovsold" numeric(38,2) NOT NULL DEFAULT 0, "cyoctsold" numeric(38,2) NOT NULL DEFAULT 0, "cysepsold" numeric(38,2) NOT NULL DEFAULT 0, "cytotsold" numeric(38,2) NOT NULL DEFAULT 0, "depositcode_tmp" character varying(255) NULL, "depositmultiplier" integer NOT NULL, "deptcode" character varying(255) NULL, "description" character varying(255) NULL, "envmultiplier" integer NOT NULL, "isdiscountallowed" character varying(255) NOT NULL DEFAULT 'No', "istaxed" character varying(255) NULL, "last1cost" numeric(38,2) NULL, "last1invoiceno" character varying(255) NULL, "last1orderdate" timestamptz NULL, "last1poseqno" integer NULL, "last1qtyreceived" integer NULL, "last1receivedate" timestamptz NULL, "last1vendorcode" character varying(255) NULL, "last2cost" numeric(38,2) NULL, "last2invoiceno" character varying(255) NULL, "last2orderdate" timestamptz NULL, "last2poseqno" integer NULL, "last2qtyreceived" integer NULL, "last2receivedate" timestamptz NULL, "last2vendorcode" character varying(255) NULL, "lowbottleprice" numeric(38,2) NULL, "outstandingposeqnumber" integer NULL, "outstandingpovendor" character varying(255) NULL, "price" numeric(38,2) NULL, "pricefuture" numeric(38,2) NULL, "print_price" character varying(255) NULL, "pyaprsold" numeric(38,2) NOT NULL, "pyaugsold" numeric(38,2) NOT NULL, "pydecsold" numeric(38,2) NOT NULL, "pyfebsold" numeric(38,2) NOT NULL, "pyjansold" numeric(38,2) NOT NULL, "pyjulsold" numeric(38,2) NOT NULL, "pyjunsold" numeric(38,2) NOT NULL, "pymarsold" numeric(38,2) NOT NULL, "pymaysold" numeric(38,2) NOT NULL, "pynovsold" numeric(38,2) NOT NULL, "pyoctsold" numeric(38,2) NOT NULL, "pysepsold" numeric(38,2) NOT NULL, "pytotsold" numeric(38,2) NULL, "qtyonhand" double precision NOT NULL, "size1" integer NULL, "status" "public"."item_status" NULL DEFAULT 'ACTIVE', "subparentitembarcode_tmp" character varying(255) NULL, "subparentitemseqno" integer NULL, "subqty" integer NOT NULL DEFAULT 0, "suggestedretail" numeric(38,2) NULL, "entity_id" bigint NULL, PRIMARY KEY ("itemseqno"), CONSTRAINT "item_entity_id_fk" FOREIGN KEY ("entity_id") REFERENCES "public"."entity" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "item_item_itemseqno_fk" FOREIGN KEY ("subparentitemseqno") REFERENCES "public"."item" ("itemseqno") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "littleroosteritem_littleroosterdepartments_name_fk" FOREIGN KEY ("deptcode") REFERENCES "public"."department" ("name") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "idx_16970_littleroosteritem_barcode_index" to table: "item"
CREATE INDEX "idx_16970_littleroosteritem_barcode_index" ON "public"."item" ("barcode");
-- Create index "idx_16970_littleroosteritem_description_index" to table: "item"
CREATE INDEX "idx_16970_littleroosteritem_description_index" ON "public"."item" ("description");
-- Create index "idx_16970_littleroosteritem_littleroosterdepartments_name_fk" to table: "item"
CREATE INDEX "idx_16970_littleroosteritem_littleroosterdepartments_name_fk" ON "public"."item" ("deptcode");
-- Create index "idx_16970_littleroosteritem_littleroosteritem_itemseqno_fk" to table: "item"
CREATE INDEX "idx_16970_littleroosteritem_littleroosteritem_itemseqno_fk" ON "public"."item" ("subparentitemseqno");
-- Create index "item_barcode2_index" to table: "item"
CREATE INDEX "item_barcode2_index" ON "public"."item" ("barcode2");
-- Create "vendor" table
CREATE TABLE "public"."vendor" ("name" character varying(255) NOT NULL, "displayname" character varying(255) NOT NULL, PRIMARY KEY ("name"));
-- Create "itemvendoritemmapping" table
CREATE TABLE "public"."itemvendoritemmapping" ("itemid" integer NOT NULL, "sku" character varying(255) NULL, "vendor" character varying(255) NOT NULL, PRIMARY KEY ("itemid", "vendor"), CONSTRAINT "itemvendoritemmapping_item_itemseqno_fk" FOREIGN KEY ("itemid") REFERENCES "public"."item" ("itemseqno") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "littleroosteritemvendoritemmapping_vendor_name_fk" FOREIGN KEY ("vendor") REFERENCES "public"."vendor" ("name") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "idx_16977_littleroosteritemvendoritemmapping_itemid_index" to table: "itemvendoritemmapping"
CREATE INDEX "idx_16977_littleroosteritemvendoritemmapping_itemid_index" ON "public"."itemvendoritemmapping" ("itemid");
-- Create index "idx_16977_littleroosteritemvendoritemmapping_vendor_name_fk" to table: "itemvendoritemmapping"
CREATE INDEX "idx_16977_littleroosteritemvendoritemmapping_vendor_name_fk" ON "public"."itemvendoritemmapping" ("vendor");
-- Create "rainforestmerchants" table
CREATE TABLE "public"."rainforestmerchants" ("name" character varying(255) NOT NULL, "merchantid" character varying(255) NOT NULL, "merchantapplicationid" character varying(255) NOT NULL, PRIMARY KEY ("name"));
-- Create index "rainforestmerchants_merchantid_index" to table: "rainforestmerchants"
CREATE INDEX "rainforestmerchants_merchantid_index" ON "public"."rainforestmerchants" ("merchantid");
-- Create "merchantdevices" table
CREATE TABLE "public"."merchantdevices" ("deviceregistrationid" character varying(255) NOT NULL, "merchantname" character varying(255) NOT NULL, PRIMARY KEY ("deviceregistrationid"), CONSTRAINT "merchantdevices_rainforestmerchants_name_fk" FOREIGN KEY ("merchantname") REFERENCES "public"."rainforestmerchants" ("name") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "idx_16982_merchantdevices_rainforestmerchants_name_fk" to table: "merchantdevices"
CREATE INDEX "idx_16982_merchantdevices_rainforestmerchants_name_fk" ON "public"."merchantdevices" ("merchantname");
-- Create "purchaseorders" table
CREATE TABLE "public"."purchaseorders" ("id" integer NOT NULL GENERATED ALWAYS AS IDENTITY, "name" character varying(2000) NULL, "status" "public"."purchaseorders_status" NOT NULL DEFAULT 'open', "createdate" timestamptz NULL DEFAULT CURRENT_TIMESTAMP, "closedate" timestamptz NULL, "invoiceid" character varying(255) NULL, "entity_id" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "purchaseorders_entity_id_fk" FOREIGN KEY ("entity_id") REFERENCES "public"."entity" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "idx_17000_purchaseorders_id_uindex" to table: "purchaseorders"
CREATE UNIQUE INDEX "idx_17000_purchaseorders_id_uindex" ON "public"."purchaseorders" ("id");
-- Set comment to table: "purchaseorders"
COMMENT ON TABLE "public"."purchaseorders" IS 'metadata about purchase orders';
-- Create "purchaseorderitems" table
CREATE TABLE "public"."purchaseorderitems" ("poid" integer NOT NULL, "itemid" integer NOT NULL, "unitsordered" integer NULL DEFAULT 0, "casesordered" integer NULL DEFAULT 0, "status" "public"."purchaseorderitems_status" NULL DEFAULT 'open', "unitsentered" integer NOT NULL DEFAULT 0, "caseqty" integer NULL DEFAULT 0, "unitcost" numeric(38,2) NOT NULL DEFAULT 0.00, "itemname" character varying(255) NULL, "size" numeric(38,2) NULL, "vendorsku" character varying(255) NULL, "vendor" character varying(255) NOT NULL, "casecost" numeric(38,2) NOT NULL DEFAULT 0.00, "receivedate" timestamptz NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("poid", "itemid", "vendor"), CONSTRAINT "purchaseorderitems_item_itemseqno_fk" FOREIGN KEY ("itemid") REFERENCES "public"."item" ("itemseqno") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "purchaseorderitems_purchaseorders_id_fk" FOREIGN KEY ("poid") REFERENCES "public"."purchaseorders" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "idx_16987_purchaseorderitems_littleroosteritem_itemseqno_fk" to table: "purchaseorderitems"
CREATE INDEX "idx_16987_purchaseorderitems_littleroosteritem_itemseqno_fk" ON "public"."purchaseorderitems" ("itemid");
-- Create index "idx_16987_purchaseorderitems_vendoritem_sku_vendor_fk" to table: "purchaseorderitems"
CREATE INDEX "idx_16987_purchaseorderitems_vendoritem_sku_vendor_fk" ON "public"."purchaseorderitems" ("vendorsku", "vendor");
-- Create "transactionclosings" table
CREATE TABLE "public"."transactionclosings" ("id" integer NOT NULL GENERATED ALWAYS AS IDENTITY, "registernumber" integer NOT NULL, "employeeid" integer NOT NULL, "opendatetime" timestamptz NOT NULL, "closedatetime" timestamptz NOT NULL, "totaltax" numeric(38,2) NOT NULL, "totalsale" numeric(38,2) NOT NULL, "totalbottlefee" numeric(38,2) NOT NULL, "totalenvironmentfee" numeric(38,2) NOT NULL, "registeropeningbalance" numeric(38,2) NULL, "registerclosingbalance" numeric(38,2) NULL, "totalcreditcardsale" numeric(38,2) NOT NULL, "totaldiscount" numeric(38,2) NOT NULL, "totalothersale" numeric(38,2) NOT NULL, "totalchecksale" numeric(38,2) NOT NULL, "totalsubtotal" numeric(38,2) NOT NULL, "entity_id" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "transactionclosings_employee_id_fk" FOREIGN KEY ("employeeid") REFERENCES "public"."employee" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "transactionclosings_entity_id_fk" FOREIGN KEY ("entity_id") REFERENCES "public"."entity" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "idx_17012_transactionclosings_employee_id_fk" to table: "transactionclosings"
CREATE INDEX "idx_17012_transactionclosings_employee_id_fk" ON "public"."transactionclosings" ("employeeid");
-- Create "transactions" table
CREATE TABLE "public"."transactions" ("amountreceived" numeric(38,2) NULL, "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY, "transactiontotal" numeric(38,2) NULL, "createddate" timestamptz NULL, "paymentform" character varying(255) NULL, "registernumber" integer NOT NULL, "creditcardamountreceived" numeric(38,2) NOT NULL, "checkamountreceived" numeric(38,2) NOT NULL, "otheramountreceived" numeric(38,2) NOT NULL, "isvoided" boolean NOT NULL DEFAULT false, "closingsid" integer NULL, "payinconfigid" character varying(255) NULL, "entity_id" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "littleroostertransactions_littleroostertransactionclosings_id_f" FOREIGN KEY ("closingsid") REFERENCES "public"."transactionclosings" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "transactions_entity_id_fk" FOREIGN KEY ("entity_id") REFERENCES "public"."entity" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "idx_17015_littleroostertransactions_closingsid_index" to table: "transactions"
CREATE INDEX "idx_17015_littleroostertransactions_closingsid_index" ON "public"."transactions" ("closingsid");
-- Create index "idx_17015_littleroostertransactions_createddate_index" to table: "transactions"
CREATE INDEX "idx_17015_littleroostertransactions_createddate_index" ON "public"."transactions" ("createddate");
-- Create "transactionitems" table
CREATE TABLE "public"."transactionitems" ("id" integer NOT NULL GENERATED ALWAYS AS IDENTITY, "quantity" integer NOT NULL, "littleroosteritemid" integer NOT NULL, "price" numeric(38,2) NOT NULL, "tax" numeric(38,2) NOT NULL, "upccode" character varying(255) NULL, "name" character varying(255) NOT NULL, "totalprice" numeric(38,2) NOT NULL, "transactionfk" integer NOT NULL, "discount" numeric(38,2) NOT NULL, "bottledeposit" numeric(38,2) NOT NULL, "environmentfee" numeric(38,2) NOT NULL, "department" character varying(255) NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "transactionsmetadata_departments_name_fk" FOREIGN KEY ("department") REFERENCES "public"."department" ("name") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "transactionsmetadata_transactions_id_fk" FOREIGN KEY ("transactionfk") REFERENCES "public"."transactions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "idx_17021_transactionsmetadata_departments_name_fk" to table: "transactionitems"
CREATE INDEX "idx_17021_transactionsmetadata_departments_name_fk" ON "public"."transactionitems" ("department");
-- Create index "idx_17021_transactionsmetadata_transactions_id_fk" to table: "transactionitems"
CREATE INDEX "idx_17021_transactionsmetadata_transactions_id_fk" ON "public"."transactionitems" ("transactionfk");
-- Create "user" table
CREATE TABLE "public"."user" ("id" character varying(255) NOT NULL, PRIMARY KEY ("id"));
-- Create "user_entity" table
CREATE TABLE "public"."user_entity" ("user_id" character varying(255) NOT NULL, "entity_id" bigint NOT NULL, "role" character varying(255) NOT NULL, PRIMARY KEY ("user_id", "entity_id"), CONSTRAINT "user_entity_entity_id_fk" FOREIGN KEY ("entity_id") REFERENCES "public"."entity" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "user_entity_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "vendoritem" table
CREATE TABLE "public"."vendoritem" ("alcohol_by_volume" double precision NULL, "case_size" integer NULL, "full_case_only" boolean NULL, "ibu" double precision NULL, "liters" double precision NULL, "size" double precision NULL, "sleeve_size" integer NULL, "vintage_year" integer NULL, "last_modified" timestamptz NOT NULL, "size_unit" character varying(50) NULL, "ttb" character varying(50) NULL, "upc" character varying(50) NULL, "product_style" character varying(100) NULL, "product_subtype" character varying(100) NULL, "product_type" character varying(100) NULL, "product_name" character varying(355) NOT NULL, "vendor_product_name" character varying(355) NULL, "parent_producer" character varying(255) NULL, "producer" character varying(255) NULL, "product_line_id" character varying(255) NULL, "sku" character varying(255) NOT NULL, "status" character varying(255) NULL, "supplier" character varying(255) NULL, "unit" character varying(255) NULL, "vendor" character varying(255) NOT NULL, PRIMARY KEY ("sku", "vendor"), CONSTRAINT "vendoritem_vendor_name_fk" FOREIGN KEY ("vendor") REFERENCES "public"."vendor" ("name") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "idx_17031_vendoritem_vendor_name_fk" to table: "vendoritem"
CREATE INDEX "idx_17031_vendoritem_vendor_name_fk" ON "public"."vendoritem" ("vendor");
-- Create index "vendoritem_upc_index" to table: "vendoritem"
CREATE INDEX "vendoritem_upc_index" ON "public"."vendoritem" ("upc");
-- Create "vendoritemprice" table
CREATE TABLE "public"."vendoritemprice" ("amended" boolean NULL, "case_post_off" double precision NULL, "case_price" double precision NULL, "list_case_price" double precision NULL, "list_unit_price" double precision NULL, "month" integer NOT NULL, "state_min_unit_price" double precision NULL, "suggested_retail_price" double precision NULL, "unit_post_off" double precision NULL, "unit_price" double precision NULL, "year" integer NOT NULL, "catalog_date" character varying(7) NULL, "last_modified" timestamptz NOT NULL, "buy_range" character varying(50) NULL, "vendor_note" character varying(50) NULL, "post_type" "public"."vendoritemprice_post_type" NULL, "sku" character varying(255) NOT NULL, "vendor" character varying(255) NOT NULL, PRIMARY KEY ("month", "year", "sku", "vendor"), CONSTRAINT "vendoritemprice_vendor_name_fk" FOREIGN KEY ("vendor") REFERENCES "public"."vendor" ("name") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "vendoritemprice_vendoritem_sku_vendor_fk" FOREIGN KEY ("sku", "vendor") REFERENCES "public"."vendoritem" ("sku", "vendor") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "idx_17036_fko7chtlemft1sq0kpi639jqwyo" to table: "vendoritemprice"
CREATE INDEX "idx_17036_fko7chtlemft1sq0kpi639jqwyo" ON "public"."vendoritemprice" ("sku", "vendor");
-- Create index "idx_17036_vendoritemprice_vendor_name_fk" to table: "vendoritemprice"
CREATE INDEX "idx_17036_vendoritemprice_vendor_name_fk" ON "public"."vendoritemprice" ("vendor");
